### PR TITLE
separate static api to new branch

### PR DESCRIPTION
**Pull request by Faelayis**

### CODE REVIEW

**Review by sctnightcore — APPROVED** [review]
let's hacktoberfest xD

**Comment by Faelayis** [comment]
require initial data created for new base branch.

[example](https://github.com/Faelayis/cmru-pca-scraper/tree/data)

**Comment by sctnightcore** [comment]
> require initial data created for new base branch.
> 
> [example](https://github.com/Faelayis/cmru-pca-scraper/tree/data)

done.

**Comment by Faelayis** [comment]
try test run github action

I think it should work.

**Comment by Faelayis** [comment]
i think it should work.

**Comment by sctnightcore** [comment]
> try test run github action
> 
> I think it should work.

If you think it works. It works.

**Pull request merged**
